"""Initial migration with User and Item models

Revision ID: 011c065f5c9f
Revises: 
Create Date: 2025-09-05 20:26:08.695081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '011c065f5c9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('keycloak_sub', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'user', ['is_active'], unique=False)
    op.create_index('idx_user_deleted', 'user', ['deleted_at'], unique=False)
    op.create_index('idx_user_email', 'user', ['email'], unique=False)
    op.create_index('idx_user_keycloak_sub', 'user', ['keycloak_sub'], unique=False)
    op.create_index('idx_user_username', 'user', ['username'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_keycloak_sub'), 'user', ['keycloak_sub'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('item',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_embedding', sa.Boolean(), nullable=False),
    sa.Column('milvus_id', sa.String(length=255), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_version', sa.String(length=50), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('item_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_category', 'item', ['category'], unique=False)
    op.create_index('idx_item_created_at', 'item', ['created_at'], unique=False)
    op.create_index('idx_item_deleted', 'item', ['deleted_at'], unique=False)
    op.create_index('idx_item_featured', 'item', ['is_featured'], unique=False)
    op.create_index('idx_item_has_embedding', 'item', ['has_embedding'], unique=False)
    op.create_index('idx_item_like_count', 'item', ['like_count'], unique=False)
    op.create_index('idx_item_milvus_id', 'item', ['milvus_id'], unique=False)
    op.create_index('idx_item_owner_id', 'item', ['owner_id'], unique=False)
    op.create_index('idx_item_public', 'item', ['is_public'], unique=False)
    op.create_index('idx_item_title', 'item', ['title'], unique=False)
    op.create_index('idx_item_view_count', 'item', ['view_count'], unique=False)
    op.create_index(op.f('ix_item_category'), 'item', ['category'], unique=False)
    op.create_index(op.f('ix_item_milvus_id'), 'item', ['milvus_id'], unique=True)
    op.create_index(op.f('ix_item_owner_id'), 'item', ['owner_id'], unique=False)
    op.create_index(op.f('ix_item_title'), 'item', ['title'], unique=False)
    op.drop_index(op.f('idx_app_config_created_at'), table_name='app_config')
    op.drop_index(op.f('idx_app_config_key'), table_name='app_config')
    op.drop_table('app_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('app_config_pkey')),
    sa.UniqueConstraint('key', name=op.f('app_config_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_app_config_key'), 'app_config', ['key'], unique=False)
    op.create_index(op.f('idx_app_config_created_at'), 'app_config', ['created_at'], unique=False)
    op.drop_index(op.f('ix_item_title'), table_name='item')
    op.drop_index(op.f('ix_item_owner_id'), table_name='item')
    op.drop_index(op.f('ix_item_milvus_id'), table_name='item')
    op.drop_index(op.f('ix_item_category'), table_name='item')
    op.drop_index('idx_item_view_count', table_name='item')
    op.drop_index('idx_item_title', table_name='item')
    op.drop_index('idx_item_public', table_name='item')
    op.drop_index('idx_item_owner_id', table_name='item')
    op.drop_index('idx_item_milvus_id', table_name='item')
    op.drop_index('idx_item_like_count', table_name='item')
    op.drop_index('idx_item_has_embedding', table_name='item')
    op.drop_index('idx_item_featured', table_name='item')
    op.drop_index('idx_item_deleted', table_name='item')
    op.drop_index('idx_item_created_at', table_name='item')
    op.drop_index('idx_item_category', table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_keycloak_sub'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index('idx_user_username', table_name='user')
    op.drop_index('idx_user_keycloak_sub', table_name='user')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_index('idx_user_deleted', table_name='user')
    op.drop_index('idx_user_active', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
