"""Add document and sensitive data detection models

Revision ID: bcfe6c9b2ca4
Revises: 011c065f5c9f
Create Date: 2025-09-06 09:29:15.471441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcfe6c9b2ca4'
down_revision: Union[str, Sequence[str], None] = '011c065f5c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.Enum('PDF', 'DOCX', name='documenttype'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', 'READY_TO_VIEW', 'HAS_SENSITIVE_DATA', name='documentstatus'), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('has_sensitive_data', sa.Boolean(), nullable=False),
    sa.Column('scan_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_created_at', 'document', ['created_at'], unique=False)
    op.create_index('idx_document_deleted', 'document', ['deleted_at'], unique=False)
    op.create_index('idx_document_document_type', 'document', ['document_type'], unique=False)
    op.create_index('idx_document_filename', 'document', ['filename'], unique=False)
    op.create_index('idx_document_has_sensitive_data', 'document', ['has_sensitive_data'], unique=False)
    op.create_index('idx_document_owner_id', 'document', ['owner_id'], unique=False)
    op.create_index('idx_document_scan_completed_at', 'document', ['scan_completed_at'], unique=False)
    op.create_index('idx_document_status', 'document', ['status'], unique=False)
    op.create_index(op.f('ix_document_owner_id'), 'document', ['owner_id'], unique=False)
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_table('sensitive_data_detection',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('data_type', sa.Enum('PERSONAL_ID', 'PHONE_NUMBER', 'EMAIL', 'ADDRESS', 'BANK_ACCOUNT', 'CREDIT_CARD', 'TAX_ID', 'SOCIAL_SECURITY', 'MEDICAL_INFO', 'FINANCIAL_INFO', 'GOVERNMENT_ID', 'CUSTOM', name='sensitivedatatype'), nullable=False),
    sa.Column('detected_text', sa.Text(), nullable=False),
    sa.Column('masked_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevel'), nullable=False),
    sa.Column('detection_pattern', sa.String(length=255), nullable=True),
    sa.Column('ai_model_used', sa.String(length=100), nullable=False),
    sa.Column('detection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('false_positive', sa.Boolean(), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensitive_data_confidence_level', 'sensitive_data_detection', ['confidence_level'], unique=False)
    op.create_index('idx_sensitive_data_created_at', 'sensitive_data_detection', ['created_at'], unique=False)
    op.create_index('idx_sensitive_data_document_id', 'sensitive_data_detection', ['document_id'], unique=False)
    op.create_index('idx_sensitive_data_false_positive', 'sensitive_data_detection', ['false_positive'], unique=False)
    op.create_index('idx_sensitive_data_reviewed', 'sensitive_data_detection', ['reviewed'], unique=False)
    op.create_index('idx_sensitive_data_type', 'sensitive_data_detection', ['data_type'], unique=False)
    op.create_index(op.f('ix_sensitive_data_detection_data_type'), 'sensitive_data_detection', ['data_type'], unique=False)
    op.create_index(op.f('ix_sensitive_data_detection_document_id'), 'sensitive_data_detection', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensitive_data_detection_document_id'), table_name='sensitive_data_detection')
    op.drop_index(op.f('ix_sensitive_data_detection_data_type'), table_name='sensitive_data_detection')
    op.drop_index('idx_sensitive_data_type', table_name='sensitive_data_detection')
    op.drop_index('idx_sensitive_data_reviewed', table_name='sensitive_data_detection')
    op.drop_index('idx_sensitive_data_false_positive', table_name='sensitive_data_detection')
    op.drop_index('idx_sensitive_data_document_id', table_name='sensitive_data_detection')
    op.drop_index('idx_sensitive_data_created_at', table_name='sensitive_data_detection')
    op.drop_index('idx_sensitive_data_confidence_level', table_name='sensitive_data_detection')
    op.drop_table('sensitive_data_detection')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_owner_id'), table_name='document')
    op.drop_index('idx_document_status', table_name='document')
    op.drop_index('idx_document_scan_completed_at', table_name='document')
    op.drop_index('idx_document_owner_id', table_name='document')
    op.drop_index('idx_document_has_sensitive_data', table_name='document')
    op.drop_index('idx_document_filename', table_name='document')
    op.drop_index('idx_document_document_type', table_name='document')
    op.drop_index('idx_document_deleted', table_name='document')
    op.drop_index('idx_document_created_at', table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
