"""Add direct authentication fields to user table

Revision ID: ea0ba4d02447
Revises: eb2319cabc94
Create Date: 2025-09-06 10:26:28.230578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0ba4d02447'
down_revision: Union[str, Sequence[str], None] = 'eb2319cabc94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('account_locked_until', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user', 'keycloak_sub',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'keycloak_sub',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'account_locked_until')
    op.drop_column('user', 'failed_login_attempts')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
