"""Add document and sensitive data detection models

Revision ID: eb2319cabc94
Revises: bcfe6c9b2ca4
Create Date: 2025-09-06 09:40:38.175965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2319cabc94'
down_revision: Union[str, Sequence[str], None] = 'bcfe6c9b2ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
